language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- stable
sudo: false
install:
- npm install
script:
- npm run travis
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
