language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- '5'
- stable
sudo: false
install:
- npm install
script:
- '[ -e key.json ] && npm run travis || false'
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_install:
- openssl aes-256-cbc -K $encrypted_a237b3635f54_key -iv $encrypted_a237b3635f54_iv
  -in key.json.enc -out key.json -d
