language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- '6'
- stable
sudo: false
env:
  FB_QUEUE_TEST_DB_URL=https://fir-queue-test.firebaseio.com
install:
- npm install
script:
- '[ -e test/key.json ] && npm run travis || false'
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_install:
- openssl aes-256-cbc -K $encrypted_a237b3635f54_key -iv $encrypted_a237b3635f54_iv
  -in test/key.json.enc -out test/key.json -d
